# Generated by Django 5.0 on 2023-12-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imaeg',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
