# Generated by Django 5.0 on 2023-12-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_product_imaeg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imaeg',
            new_name='image',
        ),
    ]
